// Course
export const UPDATE_COURSE_CRAWL_DATA = "UPDATE_COURSE_CRAWL_DATA"
export const UPDATE_COURSE_ROOT_DIR= "UPDATE_COURSE_ROOT_DIR"
export const UPDATE_SELECTED_LESSON="UPDATE_SELECTED_LESSON"

// Error
export const UPDATE_ERROR = "UPDATE_ERROR"